### PR TITLE
Respect --all-namespaces for image based gadgets

### LINKED ISSUE #3077: kubectl-gadget: `-A` flag doesn't work
The `-A` flag is intended to show events in all namespaces, however it's currently broken for image based gadgets:

There are some processes in the default namespace:

```bash 
$ ./kubectl-gadget run snapshot_process:latest --pull always
INFO[0000] Experimental features enabled
RUNTIME.CONTAINERNAME         MNTNS_ID     PID             TID             PPID            UID             GID            COMM
                              4026535590   194468          194468          194447          0               0              sh
                              4026535590   195061          195061          194468          0               0              ping
^C
```

and for sure on the kube-system one

```bash 
$ ./kubectl-gadget run snapshot_process:latest --pull always -n kube-system
INFO[0000] Experimental features enabled
RUNTIME.CONTAINERNAME         MNTNS_ID     PID             TID             PPID            UID             GID            COMM
kube-apiserver                4026535139   183927          183927          183826          0               0              kube-apiserver
kube-scheduler                4026535142   183934          183934          183866          0               0              kube-scheduler
kube-controller-manager       4026535145   183936          183936          183858          0               0              kube-controlle
etcd                          4026535153   184044          184044          184002          0               0              etcd
coredns                       4026535252   184254          184254          184208          65532           65532          coredns
kube-proxy                    4026535472   184565          184565          184480          0               0              kube-proxy
kindnet-cni                   4026535475   184568          184568          184499          0               0              kindnetd
storage-provisioner           4026535469   188164          188164          188142          0               0              storage-provis
kindnet-cni                   4026533923   187428          187428          187378          0               0              kindnetd
kube-proxy                    4026533926   187433          187433          187386          0               0              kube-proxy
^C
```

But `-A` only shows the ones from the default ns:

```bash 
$ ./kubectl-gadget run snapshot_process:latest --pull always -A
INFO[0000] Experimental features enabled
RUNTIME.CONTAINERNAME         MNTNS_ID     PID             TID             PPID            UID             GID            COMM
                              4026535590   194468          194468          194447          0               0              sh
                              4026535590   195061          195061          194468          0               0              ping
^C
``

### PR DESCRIPTION
**Pull request by burak-ok**
fixes #3077

### CODE REVIEW

File: pkg/operators/kubemanager/kubemanager.go [hunk 1]
```diff
@@ -117,10 +117,11 @@ func (k *KubeManager) ParamDescs() params.ParamDescs {
...
 		{
-			Key:         ParamNamespace,
-			Alias:       "n",
-			Description: "Show only data from pods in a given namespace",
-			ValueHint:   gadgets.K8SNamespace,
+			Key:          ParamNamespace,
+			Alias:        "n",
+			Description:  "Show only data from pods in a given namespace",
+			ValueHint:    gadgets.K8SNamespace,
+			DefaultValue: "default",
```
Comment (flyth) [inline pkg/operators/kubemanager/kubemanager.go:124]: [This](https://github.com/inspektor-gadget/inspektor-gadget/blob/fd1702ec3451c044c10ade79eba7916ec3e9b451/cmd/kubectl-gadget/utils/flags.go#L77) seems to be the legacy way of getting the namespace - I don't know if it can just be replaced by that, but I think it's better to get it from kubeconfig than just using "default". WDYT?

Comment (burak-ok) [reply pkg/operators/kubemanager/kubemanager.go:124]: Its a good idea. But I don't have an idea on top of my head how we could achieve that in a general way.

Like having operator parameters with default values dependant on the client sides files. Did I miss something?

Comment (flyth) [reply pkg/operators/kubemanager/kubemanager.go:124]: Good point - I think the initial idea was to evaluate the `ValueHint` on the client side and set/replace defaults based on that.

Comment (burak-ok) [reply pkg/operators/kubemanager/kubemanager.go:124]: I removed that commit. Doesn't have to do anything with the issue this PR wants to solve

Comment (mauriciovasquezbernal) [reply pkg/operators/kubemanager/kubemanager.go]: > Good point - I think the initial idea was to evaluate the `ValueHint` on the client side and set/replace defaults based on that.

I think we're already doing it on https://github.com/inspektor-gadget/inspektor-gadget/blob/9e8b8dc8893bb878eed602568581ef59603a8ed4/cmd/kubectl-gadget/main.go#L102-L103

**Review by mauriciovasquezbernal — APPROVED** [review]
I manually tested and it works great, thanks for the quick fix!
