### PR TITLE
operators/ebpf: Fix missing parameter default value map-fetch-interval

### LINKED ISSUE #4408: gadgets: Data isn't printed for gadgets run using a gadget instance file
I'm trying to run some gadgets using [Gadget Instance Manifests](https://inspektor-gadget.io/docs/latest/reference/manifests), some of them work, but other don't print anything to the terminal

Consider the following yaml file

```yaml
# myinstance.yaml
apiVersion: 1
kind: instance-spec
image: profile_blockio:main
name: myinstance
```

When I run `sudo ig run -f myinstance.yaml` I just an empty terminal, nothing is printed, running the gadget without the manifest file works fine:

```bash 
$ sudo ig run profile_blockio:main
latency
        µs               : count    distribution
         0 -> 1          : 0        |                                        |
         1 -> 2          : 0        |                                        |
         2 -> 4          : 0        |                                        |
         4 -> 8          : 0        |                                        |
         8 -> 16         : 0        |                                        |
        16 -> 32         : 0        |                                        |
        32 -> 64         : 0        |                                        |
        64 -> 128        : 9        |****************************************|
       128 -> 256        : 2        |********                                |
       256 -> 512        : 0        |                                        |
...
```

I tried with different gadgets, it works for tracers and snapshotters, but doesn't work for profilers nor toppers. I tried to bisect it and got the same result as back as v0.34.0.

I captured the logs in both cases:

<details>

<summary>sudo ig run profile_blockio:main -v</summary>

```bash
$ sudo ig run profile_blockio:main -v
DEBU[0000] bpf already mounted
DEBU[0000] debugfs already mounted
DEBU[0000] tracefs already mounted
DEBU[0000] Ignoring runtime "cri-o" with non-existent socketPath "/run/crio/crio.sock"
DEBU[0000] No task for "1f6d1aae21f474cebfd7d0988faccc9570f0883bbf9d95f007bdb6e80c6ddb19". Assuming it is in "created" status  container-client=containerd
DEBU[0000] No task for "3841d73cda5a4373d7b22d09ef031421527276b425ef327a3392338946278143". Assuming it is in "created" status  container-client=containerd
DEBU[0000] Runtime enricher(containerd): Skip container "1f6d1aae21f474cebfd7d0988faccc9570f0883bbf9d95f007bdb6e80c6ddb19" (ID: 1f6d1aae21f474cebfd7d0988faccc9570f0883bbf9d95f007bdb6e80c6ddb19, image: docker.io/library/busybox:latest): not running
DEBU[0000] Runtime enricher(containerd): Skip container "3841d73cda5a4373d7b22d09ef031421527276b425ef327a3392338946278143" (ID: 3841d73cda5a4373d7b22d09ef031421527276b425ef327a3392338946278143, image: docker.io/library/busybox:latest): not running
DEBU[0000] cgroups info not available on Docker for container 9757dd5ba87212edabcb7654b44228928e19c56d5dd1b31da89152d7bc70ad2d. Trying /proc/134663/cgroup as a fallback
DEBU[0000] Runtime enricher(docker): Skip container "naughty_haslett" (ID: 763b60755fca952f2f817aad716f9086850dc6469ae7bb8c38cab5d82364d216, image: jnorwood/helm-docs:v1.11.0): not running
DEBU[0000] Runtime enricher(docker): Skip container "sharp_knuth" (ID: 89b31644dfb79b07fc5ee68b02f9e8cc1700ac65c5f99db2286cb1d1098f5145, image: jnorwood/helm-docs:v1.11.0): not running
DEBU[0000] Runtime enricher(docker): Skip container "sleepy_tu" (ID: 3d454fddad3ec35cff798afc1e3fa019616e98101ac6f46689e1bea8f9ec6409, image: jnorwood/helm-docs:v1.11.0): not running
DEBU[0000] Runtime enricher(docker): Skip container "minikube" (ID: 62732349cef70376677e26d612d8ade9549f60a5f957831931186a3a9bcb1781, image: docker.io/kicbase/stable:v0.0.44): not running
DEBU[0000] container-hook: trying runtime at /bin/runc
DEBU[0000] container-hook: monitoring runtime at /bin/runc (originally /bin/runc)
DEBU[0000] container-hook: trying runtime at /usr/bin/runc
DEBU[0000] container-hook: monitoring runtime at /usr/bin/runc (originally /usr/bin/runc)
DEBU[0000] container-hook: trying runtime at /usr/sbin/runc
DEBU[0000] container-hook: monitoring runtime at /usr/sbin/runc (originally /usr/sbin/runc)
DEBU[0000] container-hook: trying runtime at /usr/local/bin/runc
DEBU[0000] container-hook: notifying : stat /usr/local/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/local/sbin/runc
DEBU[0000] container-hook: notifying : stat /usr/local/sbin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/lib/cri-o-runc/sbin/runc
DEBU[0000] container-hook: notifying : stat /usr/lib/cri-o-runc/sbin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /run/torcx/unpack/docker/bin/runc
DEBU[0000] container-hook: notifying : stat /run/torcx/unpack/docker/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/bin/crun
DEBU[0000] container-hook: notifying : stat /usr/bin/crun: no such file or directory
DEBU[0000] container-hook: trying runtime at /var/lib/rancher/k3s/data/current/bin/runc
DEBU[0000] container-hook: notifying : stat /var/lib/rancher/k3s/data/current/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /var/lib/rancher/rke2/bin/runc
DEBU[0000] container-hook: notifying : stat /var/lib/rancher/rke2/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/libexec/crio/runc
DEBU[0000] container-hook: notifying : stat /usr/libexec/crio/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/bin/conmon
DEBU[0000] container-hook: monitoring runtime at /usr/bin/conmon (originally /usr/bin/conmon)
DEBU[0000] loading metric exporters
DEBU[0000] loading log exporters
DEBU[0000] operator "oci" has priority -1000
DEBU[0000] operator "Combiner" has priority -500
DEBU[0000] operator "LocalManager" has priority -1
DEBU[0000] operator "ebpf" has priority 0
DEBU[0000] operator "formatters" has priority 0
DEBU[0000] operator "env" has priority 1
DEBU[0000] operator "UidGidResolver" has priority 5
DEBU[0000] operator "SocketEnricher" has priority 10
DEBU[0000] operator "ustack" has priority 100
DEBU[0000] operator "filter" has priority 9000
DEBU[0000] operator "sort" has priority 9500
DEBU[0000] operator "limiter" has priority 9600
DEBU[0000] operator "otel-metrics" has priority 9995
DEBU[0000] operator "otel-logs" has priority 9999
DEBU[0000] operator "cli" has priority 10000
DEBU[0000] initializing data op "oci"
DEBU[0000] image options: &{AuthOptions:{AuthFile:/var/lib/ig/config.json SecretBytes:[] InsecureRegistries:[] DisallowPulling:false} VerifyOptions:{VerifyPublicKey:true PublicKeys:[-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoDOC0gYSxZTopenGmX3ZFvQ1DSfh
Ir4EKRt5jC+mXaJ7c7J+oREskYMn/SfZdRHNSOjLTZUMDm60zpXGhkFecg==
-----END PUBLIC KEY-----
]} AllowedGadgetsOptions:{AllowedGadgets:[]} Logger:0x6fd9c80}
DEBU[0000] Using auth file "/var/lib/ig/config.json"
DEBU[0000] Couldn't find default auth file "/var/lib/ig/config.json"...
DEBU[0000] Using default docker auth file instead
DEBU[0000] $HOME: "/root"
DEBU[0002] parsing builder version: Invalid character(s) found in major number "6b35d5a"
DEBU[0002] layer > {MediaType:application/vnd.gadget.ebpf.program.v1+binary Digest:sha256:e66941273799234e4cfa5da61c43094316d9ee5396d19eb480f93f333d1124be Size:30504 URLs:[] Annotations:map[] Data:[] Platform:<nil> ArtifactType:}
DEBU[0002] found image op "ebpf"
DEBU[0002] populating mapiter "blockio___hists"
DEBU[0002] adding struct "hist_key"
DEBU[0002]  adding field "cmd_flags" (uint32) (kind: Uint32) at 0 (parent -1) ([type:__u32 type:unsigned int name:cmd_flags src:ebpf])
DEBU[0002]  adding field "dev" (uint32) (kind: Uint32) at 4 (parent -1) ([type:__u32 type:unsigned int name:dev src:ebpf])
DEBU[0002] adding struct "hist_value"
DEBU[0002]  adding field "latency" ([27]uint32) (kind: 268435464) at 0 (parent -1) ([type:gadget_histogram_slot__u32 type:__u32 type:unsigned int name:latency src:ebpf])
DEBU[0002] program "ig_profio_iss"
DEBU[0002] > type       : RawTracepoint
DEBU[0002] > attachType : None
DEBU[0002] > sectionName: raw_tp/block_rq_issue
DEBU[0002] > license    : GPL
DEBU[0002] program "ig_profio_done"
DEBU[0002] > type       : RawTracepoint
DEBU[0002] > attachType : None
DEBU[0002] > sectionName: raw_tp/block_rq_complete
DEBU[0002] > license    : GPL
DEBU[0002] program "ig_profio_ins"
DEBU[0002] > type       : RawTracepoint
DEBU[0002] > attachType : None
DEBU[0002] > sectionName: raw_tp/block_rq_insert
DEBU[0002] > license    : GPL
DEBU[0002] initializing data op "Combiner"
DEBU[0002] combiner: No targets found. Skipping combiner operator
DEBU[0002] > skipped Combiner
DEBU[0002] initializing data op "LocalManager"
DEBU[0002] > skipped LocalManager
DEBU[0002] initializing data op "ebpf"
DEBU[0002] > skipped ebpf
DEBU[0002] initializing data op "formatters"
DEBU[0002] formatterOperator inspecting datasource "blockio"
DEBU[0002] > skipped formatters
DEBU[0002] initializing data op "env"
DEBU[0002] initializing data op "UidGidResolver"
DEBU[0002] UidGidResolver inspecting datasource "blockio"
DEBU[0002] > skipped UidGidResolver
DEBU[0002] initializing data op "SocketEnricher"
DEBU[0002] > skipped SocketEnricher
DEBU[0002] initializing data op "ustack"
DEBU[0002] > skipped ustack
DEBU[0002] initializing data op "filter"
DEBU[0002] initializing data op "sort"
DEBU[0002] initializing data op "limiter"
DEBU[0002] initializing data op "otel-metrics"
DEBU[0002] enabling print for blockio
DEBU[0002] collecting metrics for data source "blockio" as "blockio"
DEBU[0002] initializing data op "otel-logs"
DEBU[0002] > skipped otel-logs
DEBU[0002] initializing data op "cli"
DEBU[0002] preparing op "oci"
DEBU[0002] preparing op "env"
DEBU[0002] preparing op "filter"
DEBU[0002] preparing op "sort"
DEBU[0002] preparing op "limiter"
DEBU[0002] preparing op "otel-metrics"
DEBU[0002] preparing op "cli"
DEBU[0002] operator "oci" has priority -1000
DEBU[0002] operator "Combiner" has priority -500
DEBU[0002] operator "LocalManager" has priority -1
DEBU[0002] operator "ebpf" has priority 0
DEBU[0002] operator "formatters" has priority 0
DEBU[0002] operator "env" has priority 1
DEBU[0002] operator "UidGidResolver" has priority 5
DEBU[0002] operator "SocketEnricher" has priority 10
DEBU[0002] operator "ustack" has priority 100
DEBU[0002] operator "filter" has priority 9000
DEBU[0002] operator "sort" has priority 9500
DEBU[0002] operator "limiter" has priority 9600
DEBU[0002] operator "otel-metrics" has priority 9995
DEBU[0002] operator "otel-logs" has priority 9999
DEBU[0002] operator "cli" has priority 10000
DEBU[0002] initializing data op "oci"
DEBU[0002] image options: &{AuthOptions:{AuthFile:/var/lib/ig/config.json SecretBytes:[] InsecureRegistries:[] DisallowPulling:false} VerifyOptions:{VerifyPublicKey:true PublicKeys:[-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoDOC0gYSxZTopenGmX3ZFvQ1DSfh
Ir4EKRt5jC+mXaJ7c7J+oREskYMn/SfZdRHNSOjLTZUMDm60zpXGhkFecg==
-----END PUBLIC KEY-----
]} AllowedGadgetsOptions:{AllowedGadgets:[]} Logger:0x6fd9c80}
DEBU[0002] Using auth file "/var/lib/ig/config.json"
DEBU[0002] Couldn't find default auth file "/var/lib/ig/config.json"...
DEBU[0002] Using default docker auth file instead
DEBU[0002] $HOME: "/root"
DEBU[0003] parsing builder version: Invalid character(s) found in major number "6b35d5a"
DEBU[0003] layer > {MediaType:application/vnd.gadget.ebpf.program.v1+binary Digest:sha256:e66941273799234e4cfa5da61c43094316d9ee5396d19eb480f93f333d1124be Size:30504 URLs:[] Annotations:map[] Data:[] Platform:<nil> ArtifactType:}
DEBU[0003] found image op "ebpf"
DEBU[0003] populating mapiter "blockio___hists"
DEBU[0003] adding struct "hist_key"
DEBU[0003]  adding field "cmd_flags" (uint32) (kind: Uint32) at 0 (parent -1) ([type:__u32 type:unsigned int name:cmd_flags src:ebpf])
DEBU[0003]  adding field "dev" (uint32) (kind: Uint32) at 4 (parent -1) ([type:__u32 type:unsigned int name:dev src:ebpf])
DEBU[0003] adding struct "hist_value"
DEBU[0003]  adding field "latency" ([27]uint32) (kind: 268435464) at 0 (parent -1) ([type:gadget_histogram_slot__u32 type:__u32 type:unsigned int name:latency src:ebpf])
DEBU[0003] program "ig_profio_ins"
DEBU[0003] > type       : RawTracepoint
DEBU[0003] > attachType : None
DEBU[0003] > sectionName: raw_tp/block_rq_insert
DEBU[0003] > license    : GPL
DEBU[0003] program "ig_profio_iss"
DEBU[0003] > type       : RawTracepoint
DEBU[0003] > attachType : None
DEBU[0003] > sectionName: raw_tp/block_rq_issue
DEBU[0003] > license    : GPL
DEBU[0003] program "ig_profio_done"
DEBU[0003] > type       : RawTracepoint
DEBU[0003] > attachType : None
DEBU[0003] > sectionName: raw_tp/block_rq_complete
DEBU[0003] > license    : GPL
DEBU[0003] initializing data op "Combiner"
DEBU[0003] combiner: No targets found. Skipping combiner operator
DEBU[0003] > skipped Combiner
DEBU[0003] initializing data op "LocalManager"
DEBU[0003] > skipped LocalManager
DEBU[0003] initializing data op "ebpf"
DEBU[0003] > skipped ebpf
DEBU[0003] initializing data op "formatters"
DEBU[0003] formatterOperator inspecting datasource "blockio"
DEBU[0003] > skipped formatters
DEBU[0003] initializing data op "env"
DEBU[0003] initializing data op "UidGidResolver"
DEBU[0003] UidGidResolver inspecting datasource "blockio"
DEBU[0003] > skipped UidGidResolver
DEBU[0003] initializing data op "SocketEnricher"
DEBU[0003] > skipped SocketEnricher
DEBU[0003] initializing data op "ustack"
DEBU[0003] > skipped ustack
DEBU[0003] initializing data op "filter"
DEBU[0003] initializing data op "sort"
DEBU[0003] initializing data op "limiter"
DEBU[0003] initializing data op "otel-metrics"
DEBU[0003] enabling print for blockio
DEBU[0003] collecting metrics for data source "blockio" as "blockio"
DEBU[0003] initializing data op "otel-logs"
DEBU[0003] > skipped otel-logs
DEBU[0003] initializing data op "cli"
DEBU[0003] preparing op "oci"
DEBU[0003] preparing op "env"
DEBU[0003] preparing op "filter"
DEBU[0003] preparing op "sort"
DEBU[0003] preparing op "limiter"
DEBU[0003] preparing op "otel-metrics"
DEBU[0003] preparing op "cli"
DEBU[0003] pre-starting op "env"
DEBU[0003] pre-starting op "filter"
DEBU[0003] pre-starting op "sort"
DEBU[0003] pre-starting op "limiter"
DEBU[0003] limiter: disabled for all data sources
DEBU[0003] pre-starting op "otel-metrics"
DEBU[0003] using local metric provider for collector "blockio"
DEBU[0003] registered field "latency" as type "histogram"
DEBU[0003] pre-starting op "cli"
DEBU[0003] subscribing to blockio-rendered
DEBU[0003] starting op "oci"
DEBU[0003] starting ebpfInstance
DEBU[0003] creating ebpf collection
DEBU[0003] Attaching raw tracepoint "ig_profio_ins" to "block_rq_insert"
DEBU[0003] Attaching raw tracepoint "ig_profio_iss" to "block_rq_issue"
DEBU[0003] Attaching raw tracepoint "ig_profio_done" to "block_rq_complete"
DEBU[0003] starting op "env"
DEBU[0003] starting op "filter"
DEBU[0003] starting op "sort"
DEBU[0003] starting op "limiter"
DEBU[0003] starting op "otel-metrics"
DEBU[0003] starting op "cli"
DEBU[0003] running...
^CDEBU[0005] got signal, cancelling context
DEBU[0005] pre-stopping op "oci"
DEBU[0005] stopping op "cli"
DEBU[0005] stopping op "otel-metrics"
DEBU[0005] shutting down metrics
DEBU[0005] stopping op "limiter"
DEBU[0005] stopping op "sort"
DEBU[0005] stopping op "filter"
DEBU[0005] stopping op "env"
DEBU[0005] stopping op "oci"
```
</details>

<details>

<summary>sudo ig run -f myinstance.yaml  -v</summary>

```bash
$ sudo ig run -f myinstance.yaml  -v
DEBU[0000] bpf already mounted
DEBU[0000] debugfs already mounted
DEBU[0000] tracefs already mounted
DEBU[0000] loading metric exporters
DEBU[0000] Ignoring runtime "cri-o" with non-existent socketPath "/run/crio/crio.sock"
DEBU[0000] No task for "1f6d1aae21f474cebfd7d0988faccc9570f0883bbf9d95f007bdb6e80c6ddb19". Assuming it is in "created" status  container-client=containerd
DEBU[0000] No task for "3841d73cda5a4373d7b22d09ef031421527276b425ef327a3392338946278143". Assuming it is in "created" status  container-client=containerd
DEBU[0000] Runtime enricher(containerd): Skip container "1f6d1aae21f474cebfd7d0988faccc9570f0883bbf9d95f007bdb6e80c6ddb19" (ID: 1f6d1aae21f474cebfd7d0988faccc9570f0883bbf9d95f007bdb6e80c6ddb19, image: docker.io/library/busybox:latest): not running
DEBU[0000] Runtime enricher(containerd): Skip container "3841d73cda5a4373d7b22d09ef031421527276b425ef327a3392338946278143" (ID: 3841d73cda5a4373d7b22d09ef031421527276b425ef327a3392338946278143, image: docker.io/library/busybox:latest): not running
DEBU[0000] cgroups info not available on Docker for container 9757dd5ba87212edabcb7654b44228928e19c56d5dd1b31da89152d7bc70ad2d. Trying /proc/134663/cgroup as a fallback
DEBU[0000] Runtime enricher(docker): Skip container "naughty_haslett" (ID: 763b60755fca952f2f817aad716f9086850dc6469ae7bb8c38cab5d82364d216, image: jnorwood/helm-docs:v1.11.0): not running
DEBU[0000] Runtime enricher(docker): Skip container "sharp_knuth" (ID: 89b31644dfb79b07fc5ee68b02f9e8cc1700ac65c5f99db2286cb1d1098f5145, image: jnorwood/helm-docs:v1.11.0): not running
DEBU[0000] Runtime enricher(docker): Skip container "sleepy_tu" (ID: 3d454fddad3ec35cff798afc1e3fa019616e98101ac6f46689e1bea8f9ec6409, image: jnorwood/helm-docs:v1.11.0): not running
DEBU[0000] Runtime enricher(docker): Skip container "minikube" (ID: 62732349cef70376677e26d612d8ade9549f60a5f957831931186a3a9bcb1781, image: docker.io/kicbase/stable:v0.0.44): not running
DEBU[0000] container-hook: trying runtime at /bin/runc
DEBU[0000] container-hook: monitoring runtime at /bin/runc (originally /bin/runc)
DEBU[0000] container-hook: trying runtime at /usr/bin/runc
DEBU[0000] container-hook: monitoring runtime at /usr/bin/runc (originally /usr/bin/runc)
DEBU[0000] container-hook: trying runtime at /usr/sbin/runc
DEBU[0000] container-hook: monitoring runtime at /usr/sbin/runc (originally /usr/sbin/runc)
DEBU[0000] container-hook: trying runtime at /usr/local/bin/runc
DEBU[0000] container-hook: notifying : stat /usr/local/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/local/sbin/runc
DEBU[0000] container-hook: notifying : stat /usr/local/sbin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/lib/cri-o-runc/sbin/runc
DEBU[0000] container-hook: notifying : stat /usr/lib/cri-o-runc/sbin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /run/torcx/unpack/docker/bin/runc
DEBU[0000] container-hook: notifying : stat /run/torcx/unpack/docker/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/bin/crun
DEBU[0000] container-hook: notifying : stat /usr/bin/crun: no such file or directory
DEBU[0000] container-hook: trying runtime at /var/lib/rancher/k3s/data/current/bin/runc
DEBU[0000] container-hook: notifying : stat /var/lib/rancher/k3s/data/current/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /var/lib/rancher/rke2/bin/runc
DEBU[0000] container-hook: notifying : stat /var/lib/rancher/rke2/bin/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/libexec/crio/runc
DEBU[0000] container-hook: notifying : stat /usr/libexec/crio/runc: no such file or directory
DEBU[0000] container-hook: trying runtime at /usr/bin/conmon
DEBU[0000] container-hook: monitoring runtime at /usr/bin/conmon (originally /usr/bin/conmon)
DEBU[0000] loading log exporters
DEBU[0000] operator "oci" has priority -1000
DEBU[0000] operator "Combiner" has priority -500
DEBU[0000] operator "LocalManager" has priority -1
DEBU[0000] operator "ebpf" has priority 0
DEBU[0000] operator "formatters" has priority 0
DEBU[0000] operator "env" has priority 1
DEBU[0000] operator "UidGidResolver" has priority 5
DEBU[0000] operator "SocketEnricher" has priority 10
DEBU[0000] operator "ustack" has priority 100
DEBU[0000] operator "filter" has priority 9000
DEBU[0000] operator "sort" has priority 9500
DEBU[0000] operator "limiter" has priority 9600
DEBU[0000] operator "otel-metrics" has priority 9995
DEBU[0000] operator "otel-logs" has priority 9999
DEBU[0000] operator "cli" has priority 10000
DEBU[0000] initializing data op "oci"
DEBU[0000] image options: &{AuthOptions:{AuthFile:/var/lib/ig/config.json SecretBytes:[] InsecureRegistries:[] DisallowPulling:false} VerifyOptions:{VerifyPublicKey:true PublicKeys:[-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoDOC0gYSxZTopenGmX3ZFvQ1DSfh
Ir4EKRt5jC+mXaJ7c7J+oREskYMn/SfZdRHNSOjLTZUMDm60zpXGhkFecg==
-----END PUBLIC KEY-----
]} AllowedGadgetsOptions:{AllowedGadgets:[]} Logger:0x6fd9c80}
DEBU[0000] Using auth file "/var/lib/ig/config.json"
DEBU[0000] Couldn't find default auth file "/var/lib/ig/config.json"...
DEBU[0000] Using default docker auth file instead
DEBU[0000] $HOME: "/root"
DEBU[0002] parsing builder version: Invalid character(s) found in major number "6b35d5a"
DEBU[0002] layer > {MediaType:application/vnd.gadget.ebpf.program.v1+binary Digest:sha256:e66941273799234e4cfa5da61c43094316d9ee5396d19eb480f93f333d1124be Size:30504 URLs:[] Annotations:map[] Data:[] Platform:<nil> ArtifactType:}
DEBU[0002] found image op "ebpf"
DEBU[0002] populating mapiter "blockio___hists"
DEBU[0002] adding struct "hist_key"
DEBU[0002]  adding field "cmd_flags" (uint32) (kind: Uint32) at 0 (parent -1) ([type:__u32 type:unsigned int name:cmd_flags src:ebpf])
DEBU[0002]  adding field "dev" (uint32) (kind: Uint32) at 4 (parent -1) ([type:__u32 type:unsigned int name:dev src:ebpf])
DEBU[0002] adding struct "hist_value"
DEBU[0002]  adding field "latency" ([27]uint32) (kind: 268435464) at 0 (parent -1) ([type:gadget_histogram_slot__u32 type:__u32 type:unsigned int name:latency src:ebpf])
DEBU[0002] program "ig_profio_iss"
DEBU[0002] > type       : RawTracepoint
DEBU[0002] > attachType : None
DEBU[0002] > sectionName: raw_tp/block_rq_issue
DEBU[0002] > license    : GPL
DEBU[0002] program "ig_profio_done"
DEBU[0002] > type       : RawTracepoint
DEBU[0002] > attachType : None
DEBU[0002] > sectionName: raw_tp/block_rq_complete
DEBU[0002] > license    : GPL
DEBU[0002] program "ig_profio_ins"
DEBU[0002] > type       : RawTracepoint
DEBU[0002] > attachType : None
DEBU[0002] > sectionName: raw_tp/block_rq_insert
DEBU[0002] > license    : GPL
DEBU[0002] initializing data op "Combiner"
DEBU[0002] combiner: No targets found. Skipping combiner operator
DEBU[0002] > skipped Combiner
DEBU[0002] initializing data op "LocalManager"
DEBU[0002] > skipped LocalManager
DEBU[0002] initializing data op "ebpf"
DEBU[0002] > skipped ebpf
DEBU[0002] initializing data op "formatters"
DEBU[0002] formatterOperator inspecting datasource "blockio"
DEBU[0002] > skipped formatters
DEBU[0002] initializing data op "env"
DEBU[0002] initializing data op "UidGidResolver"
DEBU[0002] UidGidResolver inspecting datasource "blockio"
DEBU[0002] > skipped UidGidResolver
DEBU[0002] initializing data op "SocketEnricher"
DEBU[0002] > skipped SocketEnricher
DEBU[0002] initializing data op "ustack"
DEBU[0002] > skipped ustack
DEBU[0002] initializing data op "filter"
DEBU[0002] initializing data op "sort"
DEBU[0002] initializing data op "limiter"
DEBU[0002] initializing data op "otel-metrics"
DEBU[0002] enabling print for blockio
DEBU[0002] collecting metrics for data source "blockio" as "blockio"
DEBU[0002] initializing data op "otel-logs"
DEBU[0002] > skipped otel-logs
DEBU[0002] initializing data op "cli"
DEBU[0002] preparing op "oci"
DEBU[0002] preparing op "env"
DEBU[0002] preparing op "filter"
DEBU[0002] preparing op "sort"
DEBU[0002] preparing op "limiter"
DEBU[0002] preparing op "otel-metrics"
DEBU[0002] preparing op "cli"
DEBU[0002] pre-starting op "env"
DEBU[0002] pre-starting op "filter"
DEBU[0002] pre-starting op "sort"
DEBU[0002] pre-starting op "limiter"
DEBU[0002] limiter: disabled for all data sources
DEBU[0002] pre-starting op "otel-metrics"
DEBU[0002] using local metric provider for collector "blockio"
DEBU[0002] registered field "latency" as type "histogram"
DEBU[0002] pre-starting op "cli"
DEBU[0002] subscribing to blockio-rendered
DEBU[0002] starting op "oci"
DEBU[0002] starting ebpfInstance
DEBU[0002] creating ebpf collection
DEBU[0002] Attaching raw tracepoint "ig_profio_ins" to "block_rq_insert"
DEBU[0002] Attaching raw tracepoint "ig_profio_iss" to "block_rq_issue"
DEBU[0002] Attaching raw tracepoint "ig_profio_done" to "block_rq_complete"
DEBU[0002] starting op "env"
DEBU[0002] starting op "filter"
DEBU[0002] starting op "sort"
DEBU[0002] starting op "limiter"
DEBU[0002] starting op "otel-metrics"
DEBU[0002] starting op "cli"
DEBU[0002] running...
^CDEBU[0004] got signal, cancelling context
DEBU[0004] pre-stopping op "oci"
DEBU[0004] stopping op "cli"
DEBU[0004] stopping op "otel-metrics"
DEBU[0004] shutting down metrics
DEBU[0004] stopping op "limiter"
DEBU[0004] stopping op "sort"
DEBU[0004] stopping op "filter"
DEBU[0004] stopping op "env"
DEBU[0004] stopping op "oci"
```
</details>

It seems the `sudo ig run -f myinstance.yaml  -v` is a lot shorter, like the GetGadgetInfo call isn't done.

Tried it on 684e9c49633a881

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
The current logic relies on the client to set the value for the parameters. This is done by kubectl-gadget, gadgetctl or ig by performing a call to GetGadgetInfo() to get the list of parameters and their default values. The issue here arises when using the headless mode, as in this case, the call to GetGadgetInfo() is not done, so the value for those parameters is missing if not explicitely set by the user in the gadget manifest file. This behavior causes all gadgets that depend on the "map-fetch-interval" param as it's set to 0.

The ideal solution for it should be something like 3c7f729e83ef ("pkg/gadget-service/api-helpers: Set default value for unset params"), but it doesn't work in this case these parameters are returned by the ExtraParams() method, hence they are not available when InstantiateImageOperator() is called in pkg/operators/oci-handler/oci.go.

Fixes #4408

### Testing

Run a gadget through a gadget manifest file as indicated in #4408, it should fail before this PR and work with this one.

### CODE REVIEW

**Comment by mauriciovasquezbernal** [comment]
> LGTM, tests on citest would be welcomed.

As mentioned in https://github.com/inspektor-gadget/inspektor-gadget/pull/4410#issuecomment-2847390855, It doesn't touch anything related to the CI, to a specific kernel version or cloud provider, so I think it's not needed.

File: pkg/operators/ebpf/maps.go [hunk 1]
```diff
@@ -99,7 +101,14 @@ func (i *ebpfInstance) evaluateMapParams(paramValues api.ParamValues) error {
 	globalDuration := time.Duration(0)
 	globalCount := 0
 
-	durations, err := apihelpers.GetDurationValuesPerDataSource(paramValues[ParamMapIterInterval])
+	mapIterInterval := paramValues[ParamMapIterInterval]
```
Comment (blanquicet) [inline pkg/operators/ebpf/maps.go:104]: LGTM, but it's fixing a specific use case. This is probably happening in other situations we haven't hit yet, and final solution should look like what you mentioned in the PR's description.

I'm wondering why `GetGadgetInfo` is not called when using headless mode. It means that we're not validating at all the parameters and don't provide any feedback if they are wrong? We simply print `INFO[0000] installed as "XXX"` but gadget is not actually running?

**Review by blanquicet — APPROVED** [review]
LGTM!

**Comment by mauriciovasquezbernal** [comment]
I opened a new issue #4416 to track a generic solution for it.
