### PR TITLE
container-utils/docker: populate image digest in GetContainer

### LINKED ISSUE #5463: Docker runtime enrichment does not populate `ContainerImageDigest` for new containers
## Description

When a container is created using Docker, the runtime enrichment pipeline does not populate `Runtime.ContainerImageDigest`. As a result, Docker containers are never considered fully runtime-enriched
(`BasicRuntimeMetadata.IsEnriched()` requires a non-empty `ContainerImageDigest`), and downstream consumers (events, `list-containers`, digest-based filtering, signature verification, etc.) see an empty digest for Docker workloads.

This affects only newly created containers (enriched via the container event path).

## Environment and steps to reproduce
1. Start `ig` (e.g. `trace exec`) and watch the output.
2. While `ig` is running, start a new container whose image has a local repo digest:
```
docker run --rm --name demo busybox sh -c 'echo hello'
```
 3. Observe events for the new container: `runtime.containerImageDigest` is empty, while `runtime.containerImageName` is populated.

### PR DESCRIPTION
**Pull request by dorser**
# container-utils/docker: populate image digest in GetContainer
For newly created Docker containers, the runtime enrichment pipeline never populated `Runtime.ContainerImageDigest.containerRuntimeEnricher` enriches new containers via `DockerClient.GetContainer()`, which used `DockerContainerToContainerData` that hardcoded the digest to "". Only `GetContainerDetails()` (used for already-running containers discovered at startup) actually called `getContainerImageDigest()`. As a result, Docker containers created after ig started up came through with an empty digest, and BasicRuntimeMetadata.IsEnriched() (which requires a non-empty digest) would keep treating them as not fully enriched.

This change adds a new client-aware helper `(*DockerClient).dockerContainerToContainerData` that calls the
existing `getContainerImageDigest(container.ImageID)` helper which is the same approach already used by
`GetContainerDetails`. `GetContainer` now uses it, so newly created Docker containers are enriched with the repo digest just like already-running ones. `GetContainers()` is intentionally left unchanged: the startup path already enriches via GetContainerDetails, and adding an ImageInspect call per container in GetContainers is not necessary.

Also strengthens `TestRuntimeClientInterface` to assert that `ContainerImageDigest` is non-empty in the `GetContainer` and `GetContainerDetails` subtests (the exact digest value is still not compared, to stay version-agnostic). Without this assertion, the bug was invisible to the existing test because it was zeroing the field out
before comparison.

Fixes #5463

## How to use

 1. Check out this branch and build ig.
 2. Start ig against the Docker runtime with an event-producing gadget (e.g. trace_exec) on a host where the
image has been pulled from a registry.
 3. Start a new container: docker run --rm --name demo busybox sh -c 'echo hi'
 4. Verify that events for the new container have runtime.containerImageDigest populated with a sha256:... value
 (previously empty).
 5. Also verify already-running containers (created before ig started) still show the digest. behavior there is
 unchanged.

## Testing done

Manual validation with `ig list-containers` and an trace_exec gadget against Docker, confirming `containerImageDigest` is populated for both containers created before and after ig starts.

### CODE REVIEW

File: pkg/container-utils/docker/docker.go [hunk 1]
```diff
@@ -237,7 +237,6 @@ func (c *DockerClient) Close() error {
 
 // Gets the image digest for the given image ID, if the digest exists.
 // The digest is usually only available if the image was either pulled from a registry, or if the image was pushed to a registry, which is when the manifest is generated and its digest calculated.
-// Note: This function only works for already running containers and not for containers that are being created.
```
Comment (burak-ok) [inline pkg/container-utils/docker/docker.go:240]: That comment threw me off. Nothing was wrong with the function here - it works for every docker container. Thanks for removing that

File: pkg/container-utils/docker/docker.go [hunk 2]
```diff
@@ -287,7 +285,7 @@ func DockerContainerToContainerData(container *container.Summary) *runtimeclient
 		containerName,
 		container.Image,
 		container.ImageID,
-		imageDigest,
+		c.getContainerImageDigest(container.ImageID),
```
Comment (burak-ok) [inline pkg/container-utils/docker/docker.go:288]: I guess the overhead of an additional docker client query is negligible when starting a new container

**Review by burak-ok — APPROVED** [review]
LGTM and thanks :)
