### PR TITLE
op/uidgidresolver: Do not error out when files are missing

### LINKED ISSUE #5189: Errors when running gadget trace_open:latest on Talos Linux
## Description

Deploying `gadget` on my Talos Linux cluster works, but I can't run `kubectl gadget run trace_open:latest` which produces errors due to incompatibilities with Talos.

## Environment and steps to reproduce

1. **Set-up**: 
```
talosctl cluster create
kubectl create ns gadget
kubectl label ns gadget pod-security.kubernetes.io/enforce=privileged
kubectl label ns gadget pod-security.kubernetes.io/enforce-version=latest
```

2. **Task**: `kubectl gadget run trace_open:latest`
3. **Action(s)**: 
  a. Create the Talos cluster like describe in the set-up section
  b. Deploy gadget
  c. Run the trace pod with `kubectl gadget run trace_open:latest`
4. **Error**:
```
Error: rpc error: code = Unknown desc = pre-starting operators: pre-starting operator "UidGidResolverInstance": UserGroupCache: open /etc/passwd in host file system: open /host/etc/passwd: no such file or directory
```

## Additional information

Talos is not a conventional Linux OS, and the `/etc/passwd` file doesn't exist. I believe some "pod-boot" checks need to be refactored to account for Talos.

Pinging @bbigras, who had the issue and initially reported it in November 2024.

### PR DESCRIPTION
**Pull request by burak-ok**
The passwd and group file might not always be present on the host system on some linux distributions (for example Talos)

resolves #5189

### CODE REVIEW

File: pkg/operators/uidgidresolver/usergroupcache.go [hunk 1]
```diff
@@ -70,6 +74,14 @@ func (cache *userGroupCache) Start() error {
...
 	// No uses before us, we are the first one
 	if cache.useCount == 0 {
+		if _, err := os.Stat(fullPasswdPath); os.IsNotExist(err) {
+			return fmt.Errorf("%w: %s does not exist", ErrNoUserGroupFiles, fullPasswdPath)
+		}
+
+		if _, err := os.Stat(fullGroupPath); os.IsNotExist(err) {
+			return fmt.Errorf("%w: %s does not exist", ErrNoUserGroupFiles, fullGroupPath)
+		}
+
```
Comment (mauriciovasquezbernal) [inline pkg/operators/uidgidresolver/usergroupcache.go]: Can we do this check on Init() so the whole operator is disabled? if that's not possible, what about moving these checks into `GetUserGroupCache`?

Comment (burak-ok) [reply pkg/operators/uidgidresolver/usergroupcache.go]: Depends on how often we want to show the info log message. Having it inside the Instantiate allows us to log (and potentially) show the user who is running a gadget right now that the operator is "disabled" and won't enrich it.

Comment (mauriciovasquezbernal) [reply pkg/operators/uidgidresolver/usergroupcache.go]: IMO it's too much logging for each invocation of the gadget, at least using info level. I'd say logging this on the daemon side when the operator is initialized should be good enough.
