### PR TITLE
tests: Fix usage of same ocihandler instance

### LINKED ISSUE #4661: TestInspectCmd fails a lot
```
--- FAIL: TestInspectCmd (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2e7b5e3]

goroutine 9 [running]:
testing.tRunner.func1.2({0x367f020, 0x560abe0})
	/opt/hostedtoolcache/go/1.24.4/x64/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.24.4/x64/src/testing/testing.go:1737 +0x35e
panic({0x367f020?, 0x560abe0?})
	/opt/hostedtoolcache/go/1.24.4/x64/src/runtime/panic.go:792 +0x132
github.com/inspektor-gadget/inspektor-gadget/pkg/params.(*Param).AsString(...)
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/params/params.go:488
github.com/inspektor-gadget/inspektor-gadget/pkg/operators/oci-handler.(*OciHandlerInstance).init(0xc000488600, {0x3f20360, 0xc0000deb00})
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/operators/oci-handler/oci.go:332 +0x1a3
github.com/inspektor-gadget/inspektor-gadget/pkg/operators/oci-handler.(*ociHandler).InstantiateDataOperator(0x59f4718, {0x3f20360, 0xc0000deb00}, 0xc00051c1b0)
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/operators/oci-handler/oci.go:197 +0xb99
github.com/inspektor-gadget/inspektor-gadget/pkg/gadget-context.(*GadgetContext).initAndPrepareOperators(0xc0000deb00, 0xc00051c150)
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/gadget-context/run.go:70 +0x536
github.com/inspektor-gadget/inspektor-gadget/pkg/gadget-context.(*GadgetContext).PrepareGadgetInfo(0xc0000978b8?, 0x2?)
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/gadget-context/run.go:163 +0x13
github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtime).GetGadgetInfo(0x3efe618?, {0x3f31cd8, 0xc0000deb00}, 0xd?, 0xc000097dd8?)
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/runtime/local/oci.go:26 +0x2b
github.com/inspektor-gadget/inspektor-gadget/gadgets/ci/image_inspect/test/unit.extractGadgetInfo(0x1)
	/home/runner/work/inspektor-gadget/inspektor-gadget/gadgets/ci/image_inspect/test/unit/image_inspect_test.go:234 +0xec8
github.com/inspektor-gadget/inspektor-gadget/gadgets/ci/image_inspect/test/unit.TestInspectCmd(0xc0004928c0)
	/home/runner/work/inspektor-gadget/inspektor-gadget/gadgets/ci/image_inspect/test/unit/image_inspect_test.go:60 +0x4f
testing.tRunner(0xc0004928c0, 0x3c5b0a0)
	/opt/hostedtoolcache/go/1.24.4/x64/src/testing/testing.go:1792 +0xf4
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.24.4/x64/src/testing/testing.go:1851 +0x413
```

- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/15815195281/attempts/1#summary-44572978202
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/15861467368/attempts/1#summary-44719967501
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/15856415984/attempts/2#summary-44704132707

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
The same global Ocihandler was used in all the tests, this caused issues as they this object is not thread safe. Add an explicit error to avoid the same instance being initialized multiple times and create different instances for the tests around.

Fixes #4661

### CODE REVIEW

File: gadgets/ci/image_inspect/test/unit/image_inspect_test.go [hunk 1]
```diff
@@ -196,13 +196,12 @@ func TestExtraInfoLeak(t *testing.T) {
 
 func extractGadgetInfo(extraInfo bool) (*api.GadgetInfo, error) {
 	image := gadgetrunner.GetGadgetImageName("ci/image_inspect")
+	ocihandler := ocihandler.New()
```
Comment (burak-ok) [inline gadgets/ci/image_inspect/test/unit/image_inspect_test.go]: We should name the variable something different than the package name

File: gadgets/ci/image_inspect/test/unit/image_inspect_test.go [hunk 2]
```diff
@@ -196,13 +196,12 @@ func TestExtraInfoLeak(t *testing.T) {
...
 
 	opGlobalParams := make(map[string]*params.Params)
-	ociParams := apihelpers.ToParamDescs(ocihandler.OciHandler.InstanceParams()).ToParams()
+	ociParams := apihelpers.ToParamDescs(ocihandler.InstanceParams()).ToParams()
```
Comment (burak-ok) [inline gadgets/ci/image_inspect/test/unit/image_inspect_test.go]: Before your change the `ociParams` were used as an input to the first `Init()` call. is this still needed?
If not we could move the `ociParams` to line 231, where it is needed

Comment (mauriciovasquezbernal) [reply gadgets/ci/image_inspect/test/unit/image_inspect_test.go]: It should be needed to set the default parameters.

File: pkg/operators/oci-handler/oci.go [hunk 3]
```diff
@@ -562,4 +569,4 @@ func (o *ociHandler) Priority() int {
 }
 
 // OciHandler is a singleton of ociHandler
```
Comment (burak-ok) [inline pkg/operators/oci-handler/oci.go:571]: Not so sure about this comment anymore. Now it is not a singleton

**Review by burak-ok — APPROVED** [review]
LGTM
