### PR TITLE
Validate parent TID belongs to same process in test

### LINKED ISSUE #5068: Unit tests fail with wrong parent thread id
This is a regression from #5020.

This breaks the tests:
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/19173987404/job/54817617578
```
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -13,3 +13,3 @@
        	            	    Pid: (uint32) 1,
        	            	-   Tid: (uint32) 1
        	            	+   Tid: (uint32) 42
        	            	   }
        	Test:       	TestTraceSignalGadget/sigterm
        	Messages:   	Event doesn't match
--- FAIL: TestTraceSignalGadget (0.00s)
    --- FAIL: TestTraceSignalGadget/kill (5.84s)
    --- FAIL: TestTraceSignalGadget/sigusr2 (5.62s)
    --- FAIL: TestTraceSignalGadget/sigusr1 (5.66s)
    --- FAIL: TestTraceSignalGadget/sigint (5.45s)
    --- FAIL: TestTraceSignalGadget/sigterm (5.54s)
```

The issue is the runner does not get the correct parent thread id:
```go
func (r *Runner) runLoop() {
	...
	ppid := os.Getppid()
	...
	r.Info.Proc = ebpftypes.Process{
		Comm:    r.Info.Comm,
		Pid:     uint32(r.Info.Pid),
		Tid:     uint32(r.Info.Tid),
		MntNsID: r.Info.MountNsID,
		Creds: ebpftypes.Creds{
			Uid: uint32(r.Info.Uid),
			Gid: uint32(r.Info.Gid),
		},
		Parent: ebpftypes.Parent{
			Comm: pcomm,
			Tid:  uint32(ppid),
			Pid:  uint32(ppid),
		},
	}
```

Notice how the parent tid and parent pid use the same variable. It works fine when the tests are executed from the shell because bash is single threaded. But in the failing tests, the tests are executed by vimto, which is written in Go, so it is multi-threaded. It can still work sometimes when vimto's main thread is starting the tests.

Linux does not give any procfs API to return the parent thread id. So it is not easy to fix the tests. Some other tests in this PR used the normalization function:
```
				proc := info.Proc
				utils.NormalizeProc(&proc)
```

However, it was not done for the TestTraceSignalGadget test, so it fails sometime.

I think using utils.NormalizeProc everywhere would be wrong because it is "normalizing" too much, so we would not test anymore the other fields like "comm", "pid", etc. This PR #5020 already used utils.NormalizeProc too much.

Instead, I would prefer to check if the two parent.tid (expected and actual) belong to the same process. This could be done by checking if the two `/proc/$PARENT_THREAD_ID/task/` have the same first thread in the list. We can do that in unit tests because the unit tests have access to /proc. Integration tests cannot do that because they sometimes run tests remotely (e.g. on Kubernetes).

_Originally posted by @alban in https://github.com/inspektor-gadget/inspektor-gadget/issues/5020#issuecomment-3517321353_

cc @amitschendel

### PR DESCRIPTION
**Pull request by matthyx**
# Validate parent TID belongs to same process in test

Replace strict parent.tid equality in trace_signal_test with a same-process check for parent threads to accommodate multi-threaded parent processes.

Fixes #5068

## How to use

Run tests.

## Testing done

Multiple runs with multithreading.

### CODE REVIEW

**Comment by alban** [comment]
Given that the same checks would need to be done for all unit tests, I think it should be done by a custom normalize() function. This suggested patch works as a replacement for ExpectOneEvent but many tests use ExpectAtLeastOneEvent, and if we use a normalization function, we would not need to repeat the checks.

File: gadgets/fdpass/test/unit/fdpass_test.go [hunk 1]
```diff
@@ -50,16 +50,16 @@ func TestFdpassGadget(t *testing.T) {
...
 					return &ExpectedFdpassEvent{
-						Proc:      proc,
+						Proc:      info.Proc,
 						SocketIno: inodeNum,
 						Sockfd:    uint32(sockfd),
 						Fd:        uint32(fd),
 						File:      "/dev/null",
 					}
+				}, func(expected, actual *ExpectedFdpassEvent) {
+					utils.NormalizeProcForUnitTest(&expected.Proc, &actual.Proc)
```
Comment (alban) [inline gadgets/fdpass/test/unit/fdpass_test.go]: Before commit 509e83be4a85e5faf4990bbd172430254c2aea3e, `ExpectedFdpassEvent.Proc` was not normalized at all. But after this PR, NormalizeProcForUnitTest will ignore any bugs in `ExpectedFdpassEvent.Proc.Pid` and other fields.

I think we should continue to test most fields (without normalization to ignore discrepancies). Only `ExpectedFdpassEvent.Proc.Parent.Tid` should be normalized.

File: pkg/testing/utils/utils.go [hunk 2]
```diff
@@ -165,6 +167,35 @@ func NormalizeProc(p *Process) {
...
+		expectedTgid, err1 := GetThreadGroupID(expected.Parent.Tid)
+		actualTgid, err2 := GetThreadGroupID(actual.Parent.Tid)
+
+		// If both TGIDs were successfully retrieved and they match,
+		// normalize actual parent TID to match expected
+		if err1 == nil && err2 == nil && expectedTgid == actualTgid {
+			actual.Parent.Tid = expected.Parent.Tid
+		}
+	}
+}
```
Comment (eiffel-fl) [inline pkg/testing/utils/utils.go]: Could this rather use *TID as argument instead of *Process, since we are only accessing the TID here?

File: pkg/testing/utils/utils.go [hunk 3]
```diff
@@ -271,3 +302,32 @@ func NormalizeString(f *string) {
...
+				tgid, err := strconv.ParseUint(fields[1], 10, 32)
+				if err != nil {
+					return 0, fmt.Errorf("parsing Tgid: %w", err)
+				}
+				return uint32(tgid), nil
+			}
+		}
+	}
+
+	return 0, fmt.Errorf("cannot find Tgid in %s", statusPath)
```
Comment (eiffel-fl) [inline pkg/testing/utils/utils.go]: For the CI:
```suggestion
	return 0, fmt.Errorf("finding Tgid in %s", statusPath)
```

**Comment by matthyx** [comment]
@eiffel-fl I think it's much better now

File: pkg/testing/utils/utils.go [hunk 4]
```diff
@@ -154,6 +154,35 @@ func BuildProc(comm string, uid, gid uint32) Process {
...
+	if p.Parent.Tid == 0 {
+		return
+	}
+
+	taskDir := fmt.Sprintf("/proc/%d/task", p.Parent.Tid)
+	entries, err := os.ReadDir(taskDir)
+	if err != nil {
+		// If we can't read the task dir, leave the TID as is
+		return
+	}
```
Comment (eiffel-fl) [inline pkg/testing/utils/utils.go]: I understand we cannot change the signature there due to calling context, but silencing error makes debugging harder.
Maybe only printing the error message could be a good middle ground.

File: pkg/testing/utils/utils.go [hunk 5]
```diff
@@ -154,6 +154,35 @@ func BuildProc(comm string, uid, gid uint32) Process {
...
 
+// NormalizeParentTid normalizes the parent TID to the first thread (main thread)
+// of the process by reading /proc/$tid/task/ directory. This allows comparing
+// parent TIDs that might be different threads of the same process.
+func NormalizeParentTid(p *Process) {
+	if p.Parent.Tid == 0 {
+		return
+	}
+
+	taskDir := fmt.Sprintf("/proc/%d/task", p.Parent.Tid)
```
Comment (eiffel-fl) [inline pkg/testing/utils/utils.go]: Should this use the PID instead?

**Review by eiffel-fl — COMMENTED** [review]
This looks OK, I would like to have Alban's opinion though.
My comments may miss the point, I am also wondering if these modifications should be added in all the tests, particularly as I do not understand if this failure is flaky or not (running the CI again in other PR made them pass).

File: pkg/testing/utils/utils.go (hunk 5 above)
Comment (matthyx) [reply pkg/testing/utils/utils.go]: I dunno, just followed Alban's [lead](https://github.com/inspektor-gadget/inspektor-gadget/issues/5068#issue-3612709641):

> This could be done by checking if the two /proc/$PARENT_THREAD_ID/task/ have the same first thread in the list.

File: pkg/testing/utils/utils.go [hunk 6]
```diff
@@ -154,6 +154,40 @@ func BuildProc(comm string, uid, gid uint32) Process {
...
+	entries, err := os.ReadDir(taskDir)
+	if err != nil {
+		// If we can't read the task dir, leave the TID as is
+		tb.Logf("Could not read task dir %s: %v", taskDir, err)
+		return
+	}
+
+	if len(entries) == 0 {
+		tb.Logf("No entries in task dir %s", taskDir)
```
Comment (eiffel-fl) [inline pkg/testing/utils/utils.go]: This is nice, but I think we can use Errorf(), the execution will continue but the test would be marked as failed.

File: gadgets/fdpass/test/unit/fdpass_test.go [hunk 7]
```diff
@@ -52,7 +52,7 @@ func TestFdpassGadget(t *testing.T) {
 			validateEvent: func(t *testing.T, info *utils.RunnerInfo, inodeNum uint64, sockfd int, fd int, events []ExpectedFdpassEvent) {
 				utils.ExpectAtLeastOneEvent(func(info *utils.RunnerInfo, fd int) *ExpectedFdpassEvent {
 					proc := info.Proc
-					utils.NormalizeProc(&proc)
+					utils.NormalizeParentTid(t, &proc)
```
Comment (mauriciovasquezbernal) [inline gadgets/fdpass/test/unit/fdpass_test.go]: This doesn't do anything. `proc.Parent.Tid` here is actually the parend PID:

https://github.com/inspektor-gadget/inspektor-gadget/blob/509e83be4a85e5faf4990bbd172430254c2aea3e/pkg/testing/utils/runner.go#L205

So we don't need this normalization. (same for all other gadgets doing this)

File: pkg/testing/utils/utils.go [hunk 8]
```diff
@@ -154,6 +154,40 @@ func BuildProc(comm string, uid, gid uint32) Process {
 	}
 }
 
+// NormalizeParentTid normalizes the parent TID to the first thread (main thread)
+// of the process by reading /proc/$tid/task/ directory. This allows comparing
+// parent TIDs that might be different threads of the same process.
+func NormalizeParentTid(tb testing.TB, p *Process) {
```
Comment (mauriciovasquezbernal) [inline pkg/testing/utils/utils.go]: TBH I'm not sure it's worth it to implement the test on this was as it's not fully checking the TID is the right one. IMO it'd be better just to normalize the Parent.Tid (set to 1) and create a specific test for the Parent.Tid in a single gadget that actually checks the value of the Tid (I think we'd need ebpf iterators to get the real parent TID for the test).

@alban  any opinions on this?

Comment (alban) [reply pkg/testing/utils/utils.go]: Now that I think about it, there is another problem: if the processes are short-lived, they might have already terminated by the time we execute the normalize functions. So checking in `/proc` might fail.

So @mauriciovasquezbernal 's solution might be best. Sorry for the back and forth.

Comment (matthyx) [reply pkg/testing/utils/utils.go]: done

File: gadgets/fdpass/test/unit/fdpass_test.go (hunk 7 above)
Comment (matthyx) [reply gadgets/fdpass/test/unit/fdpass_test.go]: sorry Mauricio, I don't understand what you mean here... looks like the test is failing if I completely remove the normalizations...

Comment (mauriciovasquezbernal) [reply gadgets/fdpass/test/unit/fdpass_test.go]: The previous implementation of `NormalizeParentTid` didn't have any effect when used on `info.Proc` as the value returned as already the first thread of the process. On the current implementation (setting it to 1) it has an effect and can't be removed.
