### PR TITLE
fix(`kubectl-gadget`): Show Correct Output for `runtime.containerName` on `Docker` Runtime

### LINKED ISSUE #4844: kubectl-gadget: runtime.ContainerName doesn't contain correct value on docker runtime
## Description

While using `kubectl-gadget` with `docker` runtime, `runtime.ContainerName` doesn't contain the correct value. 

## Impact

Not able to filter with runtime container name. 

## Environment and steps to reproduce

```
$ make minikube-deploy
$ ./kubectl-gadget run trace_tcp -n kube-system --fields k8s.podname,k8s.namespace,k8s.containerNAme,runtime.runtimeName,runtime.containerName
K8S.PODNAME                                                                                       K8S.NAMESPACE                                                                                     K8S.CONTAINERNAME                                                                                RUNTIME.RUNTIMENAME RUNTIME.CONTAINERNAME                                                                           
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              coredns                                                                                         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              coredns                                                                                         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              coredns                           
```
see `K8S.CONTAINERNAME` == `RUNTIME.CONTAINERNAME`. If we check the actual `runtime.containerName` using `ig` in the minikube-docker container:

```
$ make ig
$ docker cp ig minikube-docker:/bin/ig
$ minikube ssh sudo ig run trace_tcp
→ minikube ssh 'sudo ig run trace_tcp --fields=k8s.podname,k8s.namespace,k8s.containerNAme,runtime.runtimeName,runtime.containerName'
WARN[0000] No digest found for image sha256:8cf7e21541cd7a4c6270ab7eceebfc4b0991edf10be0dd54aee111d50f5c6733 
K8S.PODNAME                                                                                       K8S.NAMESPACE                                                                                     K8S.CONTAINERNAME                                                                                RUNTIME.RUNTIMENAME RUNTIME.CONTAINERNAME                                                                           
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              k8s_coredns_coredns-7db6d8ff4d-llt66_kube-system_d4d2528e-56bc-4420-aad2-94ed6bbecbee_4         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              k8s_coredns_coredns-7db6d8ff4d-llt66_kube-system_d4d2528e-56bc-4420-aad2-94ed6bbecbee_4         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              k8s_coredns_coredns-7db6d8ff4d-llt66_kube-system_d4d2528e-56bc-4420-aad2-94ed6bbecbee_4         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              k8s_coredns_coredns-7db6d8ff4d-llt66_kube-system_d4d2528e-56bc-4420-aad2-94ed6bbecbee_4         
kube-apiserver-minikube-docker                                                                    kube-system                                                                                       kube-apiserver                                                                                   docker              k8s_kube-apiserver_kube-apiserver-minikube-docker_kube-system_cfe151ceaa25454beb7618e58a8330c8_0
kube-apiserver-minikube-docker                                                                    kube-system                                                                                       kube-apiserver                                                                                   docker              k8s_kube-apiserver_kube-apiserver-minikube-docker_kube-system_cfe151ceaa25454beb7618e58a8330c8_0
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              k8s_coredns_coredns-7db6d8ff4d-llt66_kube-system_d4d2528e-56bc-4420-aad2-94ed6bbecbee_4         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              k8s_coredns_coredns-7db6d8ff4d-llt66_kube-system_d4d2528e-56bc-4420-aad2-94ed6bbecbee_4   
```
See how  `K8S.CONTAINERNAME` != `RUNTIME.CONTAINERNAME`

## Additional information

Test should be updated to verify this behavior

### PR DESCRIPTION
**Pull request by alronova**
# Add `Docker` runtime support for composed container names

In the file `pkg/container-utils/cri/cri.go`, the `buildContainerData()` function constructs container metadata from the `CRI`. It had special handling to construct the full composed name format: `k8s_<container>_<pod>_<namespace>_<uid>_<attempt>` but this was only applied to `CRI-O`.
I've added `types.RuntimeNameDocker` to the condition so the `Docker` runtime also gets the composed container name format.

## Testing done

**Before**

Command:
```zsh
kubectl gadget run trace_tcp -n kube-system --fields k8s.podname,k8s.namespace,k8s.containerName,runtime.runtimeName,runtime.containerName
```
Output:
```
K8S.PODNAME                                                                                       K8S.NAMESPACE                                                                                     K8S.CONTAINERNAME                                                                                RUNTIME.RUNTIMENAME RUNTIME.CONTAINERNAME                                                                           
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              coredns                                                                                         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              coredns                                                                                         
coredns-7db6d8ff4d-llt66                                                                          kube-system                                                                                       coredns                                                                                          docker              coredns                           
```

**After**

Command:
```zsh
kubectl gadget run trace_tcp -n kube-system --fields k8s.podname,k8s.namespace,k8s.containerName,runtime.runtimeName,runtime.containerName
```
Output:
```
K8S.PODNAME                                      K8S.NAMESPACE                                   K8S.CONTAINERNAME                               RUNTIME.RUNTIMENAME RUNTIME.CONTAINERNAME                          
etcd-minikube-docker                             kube-system                                     etcd                                            docker              k8s_etcd_etcd-minikube-docker_kube-system_02ca1
etcd-minikube-docker                             kube-system                                     etcd                                            docker              k8s_etcd_etcd-minikube-docker_kube-system_02ca1
etcd-minikube-docker                             kube-system                                     etcd                                            docker              k8s_etcd_etcd-minikube-docker_kube-system_02ca1
etcd-minikube-docker                             kube-system                                     etcd                                            docker              k8s_etcd_etcd-minikube-docker_kube-system_02ca1
coredns-66bc5c9577-dwmcr                         kube-system                                     coredns                                         docker              k8s_coredns_coredns-66bc5c9577-dwmcr_kube-syste
coredns-66bc5c9577-dwmcr                         kube-system                                     coredns                                         docker              k8s_coredns_coredns-66bc5c9577-dwmcr_kube-syste
coredns-66bc5c9577-dwmcr                         kube-system                                     coredns                                         docker              k8s_coredns_coredns-66bc5c9577-dwmcr_kube-syste
```

## Checklist
+ [x] Aligns `kubectl-gadget` `runtime.containerName` output with that of `ig`
+ [x] Adds runtime check for `Docker` identical to `CRI-O`
+ [x] Fixes #4844 
+ [x] Commits are signed-off

### CODE REVIEW

File: pkg/container-utils/cri/cri.go [hunk 1]
```diff
@@ -446,7 +446,7 @@ func buildContainerData(runtimeName types.RuntimeName, container CRIContainer, p
 	// CRI-O does not use the same container name of Kubernetes as containerd.
```
Comment (mqasimsarfraz) [inline pkg/container-utils/cri/cri.go]: Can you please update the comment here to something like:

"Docker and CRI-O use composed runtime container names (unlike containerd) that include metadata like pod UID, which isn't available via container metadata"

**Comment by alronova** [comment]
@mqasimsarfraz, thanks for the review. I have updated the code according to your suggestions.
